language: generic # undocumented except for https://github.com/travis-ci/docs-travis-ci-com/issues/910
sudo: required

services:
  - docker

script:
  - docker build -t local-test-image .
  - docker run --rm --detach --name local-test-container local-test-image
  - |
    (
        set -euo pipefail
        attempt=0
        health=unknown
        while test "${attempt}" -lt 60; do
            attempt=$[ attempt + 1 ]
            health="$(docker inspect --format='{{.State.Health.Status}}' local-test-container)"
            echo "At attempt ${attempt} health is '${health}'."
            test "${health}" != "healthy" || break
            sleep 2
        done
        test "${health}" = "healthy"
    )
