language: generic # undocumented except for https://github.com/travis-ci/docs-travis-ci-com/issues/910
sudo: required

services:
  - docker

script:
  - docker build -t local-test-image .
  - docker run --detach --name local-test-container local-test-image
  - |
    (
        set -euo pipefail
        attempt=0
        health=unknown
        while test "${attempt}" -lt 60; do
            attempt=$[ attempt + 1 ]
            status="$(docker inspect --format='{{.State.Status}}' local-test-container)"
            test "${status}" != "exited" || {
                echo "Container has exited" >&2
                break
            }
            health="$(docker inspect --format='{{.State.Health.Status}}' local-test-container)"
            echo "At attempt ${attempt} health is '${health}'."
            test "${health}" != "healthy" || break
            sleep 2
        done
        set -x
        status="$(docker inspect --format='{{.State.Status}}' local-test-container)"
        test "${status}" = "running"
        health="$(docker inspect --format='{{.State.Health.Status}}' local-test-container)"
        test "${health}" = "healthy"
    )

after_failure:
  - "docker logs local-test-container | tail -1000 | sed 's/^/local-test-container: /'"
after_success:
  - "docker logs local-test-container | tail -1000 | sed 's/^/local-test-container: /'"
